name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build
    runs-on: windows-2022
    permissions: write-all

    steps:
      - uses: actions/checkout@v6.0.0

      - uses: actions/setup-python@v6.0.0
      - uses: ilammy/msvc-dev-cmd@v1.13.0
      - uses: msys2/setup-msys2@v2.29.0
        with:
          install: >
            zip
            make
            nasm
            diffutils
            pkg-config

      - name: Build
        shell: cmd
        run: >
          set old_path="%PATH%"
          && "%VCINSTALLDIR%\Auxiliary\Build\vcvarsall.bat" x86
          && python -c "import os, sys, subprocess;
          old_path, new_path = map(lambda k: os.getenv(k).split(os.pathsep), ('old_path', 'PATH'));
          print(':'.join(
          subprocess.check_output(['cygpath', '-u', p], text=True).strip()
          for p in new_path
          if old_path.count(p) != new_path.count(p)
          ))" > path_diff
          && msys2 build.sh

      - name: Upload zip
        uses: svenstaro/upload-release-action@2.11.3
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./ffmpeg.zip
